version: 2
references:
  container_config: &container_config
    docker:
      - image: node:8.9.4
    working_directory: /home/ubuntu/nightwatch-commands/

  repo_cache_key: &repo_cache_key
    nightwatch-commands-repo-v1-{{ .Branch }}-{{ .Revision }}

  npm_cache_key: &npm_cache_key
    nightwatch-commands-npm-v1-{{ .Branch }}-{{ .Revision }}

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - *repo_cache_key

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

jobs:
  build:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: *repo_cache_key
          paths:
              - .
      - *restore_node_modules
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: *npm_cache_key
          paths:
            - /home/ubuntu/nightwatch-commands/node_modules

  unit-test:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run:
          name: Run unit tests
          command: npm test
          working_directory: /home/ubuntu/nightwatch-commands/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-test:
          requires:
              - build

